In [5]:
import pandas as pd
data1=pd.read_csv('D:\\PGP-BABI\\Capstone\\Airbnb\\Tasmania-detailed listings - final2.csv', error_bad_lines=False)
data2=pd.read_csv('D:\\PGP-BABI\\Capstone\\Airbnb\\Sentiment Scores\\All_listing_feature_sentiment - Aggr3.csv', error_bad_lines=False)
data=pd.merge(data1,data2,on='listing_id',how='inner')

In [6]:
data.head()

,listing_id,host_is_superhost,neighbourhood_cleansed,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,...,f3n,f3p,f4n,f4p,f5n,f5p,f6n,f6p,f7n,f7p
0,35644,t,Hobart,House,Private room,2,1.5,1,1,Real Bed,...,0.007447,0.335106,0.009574,0.288298,0.005319,0.221277,0.002128,0.084043,0.001064,0.064894
1,38951,t,Hobart,Townhouse,Entire home/apt,4,1.0,2,2,Real Bed,...,0.006098,0.373984,0.004065,0.432927,0.002033,0.115854,0.010163,0.079268,0.002033,0.032520
2,84581,f,Kentish,House,Entire home/apt,9,2.0,3,6,Real Bed,...,0.000000,0.490909,0.000000,0.254545,0.018182,0.181818,0.000000,0.163636,0.000000,0.036364
3,88873,t,Hobart,Townhouse,Entire home/apt,4,1.0,2,3,Real Bed,...,0.016284,0.356322,0.016284,0.362069,0.001916,0.120690,0.007663,0.067050,0.004789,0.041188
4,137808,f,Launceston,House,Entire home/apt,9,1.5,2,7,Real Bed,...,0.032015,0.350282,0.024482,0.261770,0.016949,0.114878,0.009416,0.041431,0.007533,0.022599

In [22]:
col_names = data.columns.values.tolist()
data.loc[:, 'merged'] = ""
for each_col_ind in range(1,30):
    print('Concatenating', col_names[each_col_ind])
    data.loc[:, 'merged'] = data.loc[:, 'merged'] + " " + data[col_names[each_col_ind]].astype(str)

Concatenating host_is_superhost
Concatenating neighbourhood_cleansed
Concatenating property_type
Concatenating room_type
Concatenating accommodates
Concatenating bathrooms
Concatenating bedrooms
Concatenating beds
Concatenating bed_type
Concatenating price
Concatenating security_deposit (% of price)
Concatenating cleaning_fee (% of price)
Concatenating minimum_nights
Concatenating cancellation_policy
Concatenating f0n
Concatenating f0p
Concatenating f1n
Concatenating f1p
Concatenating f2n
Concatenating f2p
Concatenating f3n
Concatenating f3p
Concatenating f4n
Concatenating f4p
Concatenating f5n
Concatenating f5p
Concatenating f6n
Concatenating f6p
Concatenating f7n

In [25]:
data['merged'].head()

0     t Hobart House Private room 2 1.5 1 1 Real Be...
1     t Hobart Townhouse Entire home/apt 4 1.0 2 2 ...
2     f Kentish House Entire home/apt 9 2.0 3 6 Rea...
3     t Hobart Townhouse Entire home/apt 4 1.0 2 3 ...
4     f Launceston House Entire home/apt 9 1.5 2 7 ...
Name: merged, dtype: object

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
# instantiating and generating the count matrix
count = CountVectorizer()
count_matrix = count.fit_transform(data['merged'])

# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [37]:
# creating a Series for the movie titles so they are associated to an ordered numerical
# list I will use in the function to match the indexes
indices = pd.Series(data.listing_id)

#  defining the function that takes in listing id 
# as input and returns the top 10 recommended listings
def recommendations(listing, cosine_sim = cosine_sim):
    
    # initializing the empty list of recommended listings
    recommended_listings = []
    
    # gettin the index of the listing that matches the listing id
    idx = indices[indices == listing].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar listings
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    # populating the list with the best 10 matching listings
    for i in top_10_indexes:
        recommended_listings.append(list(data.listing_id)[i])
        
    return recommended_listings

In [34]:
indices

0          35644
1          38951
2          84581
3          88873
4         137808
5         162081
6         252996
7         268482
8         270374
9         278045
10        292399
11        292447
12        326771
13        352015
14        356624
15        401176
16        421609
17        421709
18        434116
19        451180
20        453777
21        453815
22        485644
23        488471
24        498220
25        499959
26        502865
27        513528
28        515646
29        519737
          ...
4314    29468366
4315    29496855
4316    29516212
4317    29516976
4318    29519126
4319    29519452
4320    29547342
4321    29550081
4322    29660478
4323    29662960
4324    29747289
4325    29747349
4326    29762663
4327    29763311
4328    29766395
4329    29780448
4330    29781455
4331    29781592
4332    29786280
4333    29788062
4334    29806922
4335    29814969
4336    29826978
4337    29834244
4338    29903362
4339    29929970
4340    29946329
4341    29951405
4342    29970350
4343    30004534
Name: listing_id, Length: 4344, dtype: int64

In [39]:
recommendations(12092875)

[28424091,
 706423,
 21034523,
 16548536,
 22491140,
 21440584,
 16666596,
 29048403,
 29519452,
 27518072]